# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("VideoHunt3r")
        Form.resize(1261, 741)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #f4f6f7;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"    color: #34495e;\n"
"    min-width: 150px;\n"
"    padding: 8px;\n"
"}\n"
"/* SADECE VideoHunt3r BAŞLIK LABEL\'I */\n"
"/* SADECE VideoHunt3r BAŞLIK LABEL\'I (Diğerlerine dokunmaz) */\n"
"/* MEGA BÜYÜK BAŞLIK STİLİ */\n"
"\n"
"QPushButton#btn_search, QPushButton#btn_download {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 15px;                 \n"
"    font-weight: 600;              \n"
"    color: white;\n"
"    border: none;\n"
"    padding: 12px 24px;             \n"
"    border-radius: 6px;\n"
"    min-width: 120px;              \n"
"    text-align: center;\n"
"    margin: 0 5px;                 \n"
"}\n"
"\n"
"QPushButton#btn_search {\n"
"    background-color: #4285F4;        \n"
"}\n"
"\n"
"QPushButton#btn_search:hover {\n"
"    background-color: #3367D6;\n"
"}\n"
"\n"
"QPushButton#btn_search:pressed {\n"
"    background-color: #2A56C0;\n"
"}\n"
"\n"
"QPushButton#btn_download {\n"
"    background-color: #FF0000;         \n"
"}\n"
"\n"
"QPushButton#btn_download:hover {\n"
"    background-color: #E60000;\n"
"}\n"
"\n"
"QPushButton#btn_download:pressed {\n"
"    background-color: #CC0000;\n"
"}\n"
"QLineEdit#url_input {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 6px;\n"
"    padding: 10px 15px;\n"
"    selection-background-color: #ff0000; \n"
"    selection-color: white;             \n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QLineEdit#url_input:hover {\n"
"    border-color: #b3b3b3;\n"
"}\n"
"\n"
"QLineEdit#url_input:focus {\n"
"    border-color: #ff0000;\n"
"    background-color: #fff9f9;\n"
"}\n"
"\n"
"QLineEdit#url_input[text=\"\"] { \n"
"    color: #999999;\n"
"    font-style: italic;\n"
"}\n"
"QLabel#titleHeader {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 36px;\n"
"    font-weight: 700;\n"
"    color: #34495e;\n"
"    text-align: center;\n"
"    padding: 8px 0;\n"
"    margin: 10px 0;\n"
"    letter-spacing: 2px;\n"
"    border: none;\n"
"    background: transparent;\n"
"    position: relative;\n"
"}\n"
"\n"
"QLabel#titleHeader::after {\n"
"    content: \'\';\n"
"    position: absolute;\n"
"    bottom: 0;\n"
"    left: 50%;\n"
"    width: 80px;\n"
"    height: 3px;\n"
"    background: #4285F4;\n"
"    transform: translateX(-50%);\n"
"}\n"
"\n"
"QLabel#label_2 {\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: 500;\n"
"    color: #34495e;\n"
"    text-align: center;\n"
"    padding: 5px 0;\n"
"    margin: 5px 0 15px 0;\n"
"    background: transparent;\n"
"    border: none;\n"
"    position: relative;\n"
"}\n"
"\n"
"QLabel#label_2::before {\n"
"    content: \'•\';\n"
"    color: #4285F4;\n"
"    margin-right: 8px;\n"
"}\n"
"\n"
"QLabel#label_2::after {\n"
"    content: \'•\';\n"
"    color: #4285F4;\n"
"    margin-left: 8px;\n"
"}\n"
"QProgressBar {\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    background-color: #F0F0F0;\n"
"    text-align: center;\n"
"    color: #333333;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4285F4;\n"
"    border-radius: 4px;\n"
"}\n"
"QComboBox {\n"
"    background-color: #ecf0f1;\n"
"    border: 1px solid #95a5a6;\n"
"    border-radius: 6px;\n"
"    padding: 6px 8px;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"    border-left: 1px solid #bdc3c7;\n"
"    background-color: #bdc3c7;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/qt-project.org/styles/commonstyle/images/arrow-down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #bdc3c7;\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: #ffffff;\n"
"    font-size: 13px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"    color: #2c3e50;\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #e9ecef;\n"
"    border-radius: 4px;\n"
"    padding: 10px;  \n"
"    min-width: 250px;\n"
"    \n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3498db;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #a0a0a0;\n"
"    font-style: italic;\n"
"    font-size: 15px; \n"
"}")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(670, 110, 531, 291))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.titleHeader = QtWidgets.QLabel(Form)
        self.titleHeader.setGeometry(QtCore.QRect(480, 0, 261, 101))
        self.titleHeader.setStyleSheet("")
        self.titleHeader.setObjectName("titleHeader")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 301, 61))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 120, 177, 607))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.titleLabel.setStyleSheet("")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.channelNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.channelNameLabel.setStyleSheet("")
        self.channelNameLabel.setObjectName("channelNameLabel")
        self.verticalLayout.addWidget(self.channelNameLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.layoutWidget)
        self.descriptionLabel.setStyleSheet("")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.channelUrlLabel = QtWidgets.QLabel(self.layoutWidget)
        self.channelUrlLabel.setStyleSheet("")
        self.channelUrlLabel.setObjectName("channelUrlLabel")
        self.verticalLayout.addWidget(self.channelUrlLabel)
        self.viewCountLabel = QtWidgets.QLabel(self.layoutWidget)
        self.viewCountLabel.setStyleSheet("")
        self.viewCountLabel.setObjectName("viewCountLabel")
        self.verticalLayout.addWidget(self.viewCountLabel)
        self.likeCountLabel = QtWidgets.QLabel(self.layoutWidget)
        self.likeCountLabel.setStyleSheet("")
        self.likeCountLabel.setObjectName("likeCountLabel")
        self.verticalLayout.addWidget(self.likeCountLabel)
        self.commentCountLabel = QtWidgets.QLabel(self.layoutWidget)
        self.commentCountLabel.setStyleSheet("")
        self.commentCountLabel.setObjectName("commentCountLabel")
        self.verticalLayout.addWidget(self.commentCountLabel)
        self.dislikeCountLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dislikeCountLabel.setStyleSheet("")
        self.dislikeCountLabel.setObjectName("dislikeCountLabel")
        self.verticalLayout.addWidget(self.dislikeCountLabel)
        self.durationLabel = QtWidgets.QLabel(self.layoutWidget)
        self.durationLabel.setStyleSheet("")
        self.durationLabel.setObjectName("durationLabel")
        self.verticalLayout.addWidget(self.durationLabel)
        self.liveStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.liveStatusLabel.setStyleSheet("")
        self.liveStatusLabel.setObjectName("liveStatusLabel")
        self.verticalLayout.addWidget(self.liveStatusLabel)
        self.ageLimitLabel = QtWidgets.QLabel(self.layoutWidget)
        self.ageLimitLabel.setStyleSheet("")
        self.ageLimitLabel.setObjectName("ageLimitLabel")
        self.verticalLayout.addWidget(self.ageLimitLabel)
        self.availabilityLabel = QtWidgets.QLabel(self.layoutWidget)
        self.availabilityLabel.setStyleSheet("")
        self.availabilityLabel.setObjectName("availabilityLabel")
        self.verticalLayout.addWidget(self.availabilityLabel)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setEnabled(True)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 118, 381, 619))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.title_le.setEnabled(True)
        self.title_le.setMouseTracking(True)
        self.title_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.title_le.setStyleSheet("")
        self.title_le.setText("")
        self.title_le.setReadOnly(True)
        self.title_le.setObjectName("title_le")
        self.verticalLayout_2.addWidget(self.title_le)
        self.channel_name_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.channel_name_le.setEnabled(True)
        self.channel_name_le.setMouseTracking(True)
        self.channel_name_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.channel_name_le.setStyleSheet("")
        self.channel_name_le.setText("")
        self.channel_name_le.setReadOnly(True)
        self.channel_name_le.setObjectName("channel_name_le")
        self.verticalLayout_2.addWidget(self.channel_name_le)
        self.description_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.description_le.setEnabled(True)
        self.description_le.setMouseTracking(True)
        self.description_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.description_le.setStyleSheet("")
        self.description_le.setText("")
        self.description_le.setReadOnly(True)
        self.description_le.setObjectName("description_le")
        self.verticalLayout_2.addWidget(self.description_le)
        self.channel_url_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.channel_url_le.setEnabled(True)
        self.channel_url_le.setMouseTracking(True)
        self.channel_url_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.channel_url_le.setStyleSheet("")
        self.channel_url_le.setText("")
        self.channel_url_le.setReadOnly(True)
        self.channel_url_le.setObjectName("channel_url_le")
        self.verticalLayout_2.addWidget(self.channel_url_le)
        self.view_count_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.view_count_le.setEnabled(True)
        self.view_count_le.setMouseTracking(True)
        self.view_count_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.view_count_le.setStyleSheet("")
        self.view_count_le.setText("")
        self.view_count_le.setReadOnly(True)
        self.view_count_le.setObjectName("view_count_le")
        self.verticalLayout_2.addWidget(self.view_count_le)
        self.like_count_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.like_count_le.setEnabled(True)
        self.like_count_le.setMouseTracking(True)
        self.like_count_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.like_count_le.setStyleSheet("")
        self.like_count_le.setText("")
        self.like_count_le.setReadOnly(True)
        self.like_count_le.setObjectName("like_count_le")
        self.verticalLayout_2.addWidget(self.like_count_le)
        self.comment_count_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.comment_count_le.setEnabled(True)
        self.comment_count_le.setMouseTracking(True)
        self.comment_count_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comment_count_le.setStyleSheet("")
        self.comment_count_le.setText("")
        self.comment_count_le.setReadOnly(True)
        self.comment_count_le.setObjectName("comment_count_le")
        self.verticalLayout_2.addWidget(self.comment_count_le)
        self.dislike_count_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.dislike_count_le.setEnabled(True)
        self.dislike_count_le.setMouseTracking(True)
        self.dislike_count_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dislike_count_le.setStyleSheet("")
        self.dislike_count_le.setText("")
        self.dislike_count_le.setReadOnly(True)
        self.dislike_count_le.setObjectName("dislike_count_le")
        self.verticalLayout_2.addWidget(self.dislike_count_le)
        self.duration_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.duration_le.setEnabled(True)
        self.duration_le.setMouseTracking(True)
        self.duration_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.duration_le.setStyleSheet("")
        self.duration_le.setText("")
        self.duration_le.setReadOnly(True)
        self.duration_le.setObjectName("duration_le")
        self.verticalLayout_2.addWidget(self.duration_le)
        self.live_status_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.live_status_le.setEnabled(True)
        self.live_status_le.setMouseTracking(True)
        self.live_status_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.live_status_le.setStyleSheet("")
        self.live_status_le.setText("")
        self.live_status_le.setReadOnly(True)
        self.live_status_le.setObjectName("live_status_le")
        self.verticalLayout_2.addWidget(self.live_status_le)
        self.age_limit_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.age_limit_le.setEnabled(True)
        self.age_limit_le.setMouseTracking(True)
        self.age_limit_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.age_limit_le.setStyleSheet("")
        self.age_limit_le.setText("")
        self.age_limit_le.setReadOnly(True)
        self.age_limit_le.setObjectName("age_limit_le")
        self.verticalLayout_2.addWidget(self.age_limit_le)
        self.avaiblity_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.avaiblity_le.setEnabled(True)
        self.avaiblity_le.setMouseTracking(True)
        self.avaiblity_le.setFocusPolicy(QtCore.Qt.NoFocus)
        self.avaiblity_le.setStyleSheet("")
        self.avaiblity_le.setText("")
        self.avaiblity_le.setReadOnly(True)
        self.avaiblity_le.setObjectName("avaiblity_le")
        self.verticalLayout_2.addWidget(self.avaiblity_le)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(740, 450, 381, 261))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.url_input = QtWidgets.QLineEdit(self.layoutWidget2)
        self.url_input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.url_input.setObjectName("url_input")
        self.verticalLayout_3.addWidget(self.url_input)
        self.btn_download = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout_3.addWidget(self.btn_download)
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout_3.addWidget(self.btn_search)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "VideoHunt3r"))
        self.titleHeader.setText(_translate("Form", "VideoHunt3r"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Basic video information</span></p></body></html>"))
        self.titleLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Title</span></p></body></html>"))
        self.channelNameLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Channel Name</span></p></body></html>"))
        self.descriptionLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Description</span></p></body></html>"))
        self.channelUrlLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Channel Url</span></p></body></html>"))
        self.viewCountLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">View Count</span></p></body></html>"))
        self.likeCountLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Like Count</span></p></body></html>"))
        self.commentCountLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Comment Count</span></p></body></html>"))
        self.dislikeCountLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Dislike Count</span></p></body></html>"))
        self.durationLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Duration</span></p></body></html>"))
        self.liveStatusLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Live Status</span></p></body></html>"))
        self.ageLimitLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Age Limit</span></p></body></html>"))
        self.availabilityLabel.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Availability</span></p></body></html>"))
        self.btn_download.setText(_translate("Form", "Download"))
        self.btn_search.setText(_translate("Form", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
